# Generated by Django 3.2.4 on 2021-06-21 04:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone number')),
                ('active', models.BooleanField(default=True, verbose_name='Notification')),
                ('add_date', models.DateField(default=datetime.date(2021, 6, 21), verbose_name='added date')),
                ('edit_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='status')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='sD')),
                ('end_date', models.DateTimeField(default=datetime.datetime(2021, 6, 21, 10, 3, 31, 570735), verbose_name='eD')),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='app1.subscribers', verbose_name='Receiver')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='app1.subscribers', verbose_name='Sender')),
            ],
        ),
    ]
